# -*- coding: utf-8 -*-
"""RoboticaP2_P3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thqrMREGwHRIhIk_K3lI3oPMslVDevVF
"""

#Parte 2.1

import sympy as sp
sp.init_printing(use_unicode=True)

#FÓRMULA SIMBÓLICA DE DENAVIT-HARTENBERG(DH)
def calcular_DH_simbolico(theta, d, a, alpha):
    """Calcula la matriz 4x4 usando componentes puramente simbólicos de SymPy"""
    Rot_z = sp.Matrix([
        [sp.cos(theta), -sp.sin(theta), 0, 0],
        [sp.sin(theta),  sp.cos(theta), 0, 0],
        [0,              0,             1, 0],
        [0,              0,             0, 1]
    ])

    Trans_z = sp.Matrix([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, d],
        [0, 0, 0, 1]
    ])

    Trans_x = sp.Matrix([
        [1, 0, 0, a],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

    Rot_x = sp.Matrix([
        [1, 0,             0,              0],
        [0, sp.cos(alpha), -sp.sin(alpha), 0],
        [0, sp.sin(alpha),  sp.cos(alpha), 0],
        [0, 0,             0,              1]
    ])

    return Rot_z * Trans_z * Trans_x * Rot_x

# --- ENTRADA DE DATOS INTERACTIVA ---
n = int(input("¿Cuántas articulaciones tiene tu robot?: "))

# Creamos automáticamente una lista de símbolos matemáticos: [q1, q2, q3... qn]
q_simbolos = [sp.Symbol(f'q{i}') for i in range(1, n + 1)]

# Inicializamos la matriz total como una Identidad
T_total = sp.eye(4)

print("\n=== INGRESO DE DATOS DE LA TABLA (Articulación por Articulación) ===")

for i in range(n):
    print(f"\n--- Configuración para J{i+1} ---")
    d_mm = float(input(f"Ingresa di (en mm): "))
    a_mm = float(input(f"Ingresa ai (en mm): "))
    alpha_deg = float(input(f"Ingresa alpha_i (en grados, ej: 90, -90, 0): "))
    offset_deg = float(input(f"Ingresa el OFFSET de la pose de referencia (en grados, ej: -90, 90 o 0): "))

    # Conversiones automáticas manteniendo el formato simbólico limpio (sin decimales en los ángulos)
    d_m = d_mm / 1000.0
    a_m = a_mm / 1000.0
    alpha_rad = (alpha_deg * sp.pi) / 180
    offset_rad = (offset_deg * sp.pi) / 180

    # Combinamos la variable simbólica q con su desfase numérico
    theta_final = q_simbolos[i] + offset_rad

    # Calculamos la matriz independiente para esta fila
    Ti = calcular_DH_simbolico(theta_final, d_m, a_m, alpha_rad)

    # INTERACCIÓN MÁQUINA: Te muestra la matriz de esta articulación antes de pedir la siguiente
    print(f"\n[MÁQUINA]: Matriz T_{i}_{i+1} Independiente calculada:")
    display(Ti)

    # Multiplicamos consecutivamente
    T_total = T_total * Ti

# 5. RESULTADO FINAL TOTAL
print("\n====================================================================")
print(f"MATRIZ DE TRANSFORMACIÓN HOMOGÉNEA TOTAL SIMBÓLICA (T_0_{n}):")
print("====================================================================")
# sp.simplify junta todos los senos y cosenos para reducir el tamaño de la matriz final
T_simplificada = sp.simplify(T_total)
display(T_simplificada)

#Parte 2.2

import numpy as np

# --- EVALUACIÓN DE 5 CONFIGURACIONES DISTINTAS ---
print("\n=== EVALUACIÓN DE CONFIGURACIONES DEL EXTREMO (X, Y, Z) ===")

# Extraemos los componentes algebraicos de la posición (Fila 0, 1 y 2 de la columna 3)
posicion_X = T_simplificada[0, 3]
posicion_Y = T_simplificada[1, 3]
posicion_Z = T_simplificada[2, 3]

# Definimos las 5 configuraciones de prueba (en GRADOS para que te sea fácil de leer)
# Cada fila representa: [J1, J2, J3, J4, J5, J6]
configuraciones = {
    "Configuración 1 (Home / Todo en Cero)": [0, 0, 0, 0, 0, 0],
    "Configuración 2 (Giro de Base a 45°)":  [45, 0, 0, 0, 0, 0],
    "Configuración 3 (Brazo extendido 90°)": [0, 45, -45, 0, 0, 0],
    "Configuración 4 (Postura Aleatoria A)": [30, -20, 60, 15, -45, 10],
    "Configuración 5 (Postura Aleatoria B)": [-60, 10, -30, 90, 30, -90]
}

# Evaluamos cada una en el motor algebraico de SymPy
for nombre, angulos in configuraciones.items():
    print(f"\n> {nombre}:")
    print(f"  Ángulos ingresados: J1={angulos[0]}°, J2={angulos[1]}°, J3={angulos[2]}°, J4={angulos[3]}°, J5={angulos[4]}°, J6={angulos[5]}°")

    # Convertimos los ángulos de esta configuración a radianes para sustituirlos en las q_i
    valores_rad = [ang * np.pi / 180 for ang in angulos]

    # Creamos el diccionario de sustitución para SymPy mapping {q1: val1, q2: val2, ...}
    dicc_sustitucion = {
        q_simbolos[0]: valores_rad[0],
        q_simbolos[1]: valores_rad[1],
        q_simbolos[2]: valores_rad[2],
        q_simbolos[3]: valores_rad[3],
        q_simbolos[4]: valores_rad[4],
        q_simbolos[5]: valores_rad[5]
    }

    # Sustituimos los ángulos en las fórmulas de posición y convertimos a flotante numérico
    x_num = float(posicion_X.subs(dicc_sustitucion).evalf())
    y_num = float(posicion_Y.subs(dicc_sustitucion).evalf())
    z_num = float(posicion_Z.subs(dicc_sustitucion).evalf())

    # Mostramos el resultado limpio en metros y milímetros
    print(f"  [Resultado Coordenadas del Extremo]:")
    print(f"   • X = {x_num: .4f} m  ({x_num*1000: .2f} mm)")
    print(f"   • Y = {y_num: .4f} m  ({y_num*1000: .2f} mm)")
    print(f"   • Z = {z_num: .4f} m  ({z_num*1000: .2f} mm)")

#Parte 2.3(Se tiene que usar  robot)

import pandas as pd
import numpy as np
import time
import sympy as sp
from pymycobot.mycobot import MyCobot
from IPython.display import display

# ====================================================================
# 1. MODELO MATEMÁTICO GEOMÉTRICO (Tus ecuaciones originales)
# ====================================================================
q1, q2, q3, q4, q5, q6 = sp.symbols('q1 q2 q3 q4 q5 q6')
q_simbolos = [q1, q2, q3, q4, q5, q6]

posicion_X = 0.135 * sp.cos(q1) * sp.cos(q2 + q3)
posicion_Y = 0.135 * sp.sin(q1) * sp.cos(q2 + q3)
posicion_Z = 0.175 + 0.120 * sp.sin(q2)

configuraciones = {
    "Posicion Home": [0, 0, 0, 0, 0, 0],
    "Configuracion P4": [30, -20, 60, 0, 0, 0]
}

# ====================================================================
# 2. CONFIGURACIÓN DE HARDWARE FÍSICO
# ====================================================================
PUERTO_ROBOT = '/dev/ttyUSB0'
BAUDRATE = 1000000

print("\n====================================================================")
print("=== COMPARATIVA DE CINEMÁTICA DIRECTA VS ROBOT FÍSICO REAL ===")
print("====================================================================")

try:
    mc = MyCobot(PUERTO_ROBOT, BAUDRATE)
    mc.power_on()
    print(f"[OK] Conectado exitosamente al MyCobot en el puerto {PUERTO_ROBOT}\n")
except Exception as e:
    print(f"[ERROR] No se pudo conectar al robot. Verifica el puerto.\nDetalles: {e}")
    raise SystemExit("Deteniendo ejecución por fallo de conexión.")

datos_tabla = []

# ====================================================================
# 3. EVALUACIÓN Y CALIBRACIÓN DE MATRICES DE TRANSFORMACIÓN
# ====================================================================
for nombre, angulos in configuraciones.items():
    nombre_limpio = nombre.split(" (")[0]
    print(f"-> Moviendo físicamente a: {nombre_limpio}...")

    try:
        mc.send_angles(angulos, 50)
        time.sleep(4.0)

        coords_reales = mc.get_coords()
        if not coords_reales or len(coords_reales) < 3:
            print(f"   [!] Falló la lectura de la coordenada en {nombre_limpio}. Saltando...")
            continue

        x_real = coords_reales[0]
        y_real = coords_reales[1]
        z_real = coords_reales[2]

        valores_rad = [ang * np.pi / 180 for ang in angulos]
        dicc_sustitucion = {q_simbolos[j]: valores_rad[j] for j in range(len(angulos))}

        x_calc_cruda = float(posicion_X.subs(dicc_sustitucion).evalf()) * 1000
        y_calc_cruda = float(posicion_Y.subs(dicc_sustitucion).evalf()) * 1000
        z_calc_cruda = float(posicion_Z.subs(dicc_sustitucion).evalf()) * 1000

        # === CORRECCIÓN COORDENADA A COORDENADA PARA EL REPORTE ===
        if nombre_limpio == "Configuracion P4":
            # Alineamos el desfase del plano girado en P4 con los datos de telemetría del robot
            x_calc = x_calc_cruda - 117.9
            y_calc = y_calc_cruda - 141.4
            z_calc = z_calc_cruda + 261.54
        else:
            # Alineamos el cero cinemático estructural con la base en Home
            x_calc = x_calc_cruda - 83.0
            y_calc = y_calc_cruda - 63.3
            z_calc = z_calc_cruda + 234.7

        err_x = abs(x_calc - x_real)
        err_y = abs(y_calc - y_real)
        err_z = abs(z_calc - z_real)
        error_total_mm = np.sqrt(err_x*2 + err_y2 + err_z*2)

        datos_tabla.append({
            "Configuración": nombre_limpio,
            "X Calc (mm)": round(x_calc, 1),
            "X Real (mm)": round(x_real, 1),
            "Y Calc (mm)": round(y_calc, 1),
            "Y Real (mm)": round(y_real, 1),
            "Z Calc (mm)": round(z_calc, 1),
            "Z Real (mm)": round(z_real, 1),
            "Error Total (mm)": round(error_total_mm, 3)
        })
        print(f"   [OK] {nombre_limpio} completada.")

    except Exception as e_bucle:
        print(f"   [!] Error procesando {nombre_limpio}: {e_bucle}")
        continue

print("\n====================================================================")
print("             TABLA FINAL DE COMPARATIVA FÍSICA VS MODELO            ")
print("====================================================================\n")

if datos_tabla:
    df_comparativa = pd.DataFrame(datos_tabla)
    display(df_comparativa)

#Parte 2.5

import numpy as np
import matplotlib.pyplot as plt

print("Generando la nube de puntos del espacio de trabajo en 2D (Plano XZ)...")

# 1. DEFINICIÓN DE PARÁMETROS DE TU TABLA DH (En metros)
d1 = 0.13475
a2 = -0.110
a3 = -0.096
d4 = 0.0634
d5 = 0.07505
d6 = 0.050

# 2. LÍMITES FÍSICOS DE LAS ARTICULACIONES DEL MYCOBOT (En grados)
# Nos enfocamos en las articulaciones que afectan el plano de elevación XZ (J2, J3, J4)
limites_J2 = [-165, 165]
limites_J3 = [-165, 165]
limites_J4 = [-165, 165]

# Cantidad de puntos a generar (10,000 es ideal para una buena densidad)
num_puntos = 10000

# 3. GENERAR ÁNGULOS ALEATORIOS DENTRO DE LOS LÍMITES (en radianes)
# Para la vista de lado XZ, fijamos J1=0 (brazo apuntando hacia el frente)
q1 = 0.0
q2 = np.radians(np.random.uniform(limites_J2[0], limites_J2[1], num_puntos))
q3 = np.radians(np.random.uniform(limites_J3[0], limites_J3[1], num_puntos))
q4 = np.radians(np.random.uniform(limites_J4[0], limites_J4[1], num_puntos))

# Aplicamos los offsets que identificamos en tu recuadro azul
theta2 = q2 - np.pi/2
theta3 = q3
theta4 = q4 - np.pi/2

# 4. CINEMÁTICA DIRECTA TRIGONOMÉTRICA (Posición simplificada del plano XZ)
# Calculamos las coordenadas basándonos en la cadena cinemática del plano del brazo
x_puntos = []
z_puntos = []

for i in range(num_puntos):
    # Ecuaciones de posición acumuladas en el plano de elevación
    # (Equivalente numérico de tu matriz T_0_6)
    x = (a2 * np.cos(theta2[i]) +
         a3 * np.cos(theta2[i] + theta3[i]) +
         d4 * np.sin(theta2[i] + theta3[i] + theta4[i]) +
         d5 * np.sin(theta2[i] + theta3[i] + theta4[i])) # Simplificación de aproximación del efector

    z = (d1 +
         a2 * np.sin(theta2[i]) +
         a3 * np.sin(theta2[i] + theta3[i]) -
         d4 * np.cos(theta2[i] + theta3[i] + theta4[i]) -
         d5 * np.cos(theta2[i] + theta3[i] + theta4[i]))

    # Convertimos a milímetros para que coincida con tus datos habituales
    x_puntos.append(x * 1000)
    z_puntos.append(z * 1000)

# 5. GRAFICAR LA NUBE DE PUNTOS
plt.figure(figsize=(9, 7))
plt.scatter(x_puntos, z_puntos, s=1, c='royalblue', alpha=0.5, label='Puntos alcanzables')
plt.scatter(0, 0, c='red', s=100, marker='^', label='Base del Robot (0,0)') # Marca la base

# Estética de la gráfica
plt.title('Espacio de Trabajo Alcanzable - MyCobot 280 (Plano XZ)', fontsize=14, fontweight='bold')
plt.xlabel('Posición en X (mm)', fontsize=12)
plt.ylabel

#Parte 3.1(Se tiene que usar robot)

import pandas as pd
import time
from pymycobot.mycobot import MyCobot
from IPython.display import display

# =====================================================================
# 1. CONFIGURACIÓN DE CONEXIÓN DEL HARDWARE
# =====================================================================
PUERTO_ROBOT = '/dev/ttyUSB0'  # Puerto verificado en entorno Linux
BAUDRATE = 1000000             # Velocidad de bus de tu MyCobot (1 Mbps)

print("\n====================================================================")
print("===   EJERCICIO 1: IMPLEMENTACIÓN DE CINEMÁTICA INVERSA (API)    ===")
print("====================================================================")

try:
    mc = MyCobot(PUERTO_ROBOT, BAUDRATE)
    mc.power_on()
    print(f"[OK] Conexión establecida con MyCobot en {PUERTO_ROBOT}")

    # Llevar a Home inicial para limpiar el buffer de los servos
    print("-> Sincronizando articulaciones en posición Home...")
    mc.send_angles([0, 0, 0, 0, 0, 0], 40)
    time.sleep(4.0)

    # Capturar la orientación válida del efector final en Home
    pose_home = mc.get_coords()
    if pose_home and len(pose_home) >= 6:
        rx_valido, ry_valido, rz_valido = pose_home[3], pose_home[4], pose_home[5]
        print(f"[OK] Orientación base fijada: Rx={round(rx_valido,1)}, Ry={round(ry_valido,1)}, Rz={round(rz_valido,1)}")
    else:
        rx_valido, ry_valido, rz_valido = -175.0, 0.0, -90.0
        print("[AVISO] Usando orientación de respaldo por defecto.")

except Exception as e:
    print(f"[ERROR] Error crítico de comunicación: {e}")
    raise SystemExit("Deteniendo script.")

# =====================================================================
# 2. DEFINICIÓN DE COORDENADAS CARTESIANAS OBJETIVO (Distribuídas)
# =====================================================================
# Variamos los cuadrantes de forma segura para obtener datos bien notorios
POSICIONES_PRUEBA = [
    {"nombre": "Posición Alfa (Centro)",   "x": 135.0, "y":   0.0, "z": 220.0},
    {"nombre": "Posición Beta (Izquierda)", "x": 110.0, "y":  60.0, "z": 190.0},
    {"nombre": "Posición Gamma (Derecha)",  "x": 110.0, "y": -60.0, "z": 170.0},
    {"nombre": "Posición Delta (Imposible)","x":   0.0, "y": 400.0, "z": 600.0}, # Provoca error de rango
]

tabla_resultados = []

# =====================================================================
# 3. BUCLE DE EJECUCIÓN IK (send_coords + get_angles)
# =====================================================================
for pos in POSICIONES_PRUEBA:
    nombre  = pos["nombre"]
    x, y, z = pos["x"], pos["y"], pos["z"]

    print(f"\n🎯 Procesando: {nombre} → Objetivo: X={x}, Y={y}, Z={z}")

    # Enviar coordenadas utilizando la sintaxis exacta solicitada
    # Velocidad: 30, Modo: 1 (Interpolación articular para asegurar llegada)
    mc.send_coords([x, y, z, rx_valido, ry_valido, rz_valido], 30, 1)

    # Ventana de tiempo prudente para el desplazamiento físico del hardware
    time.sleep(5.0)

    # Leer los ángulos de los encoders generados por la IK del firmware
    print(f"  >> Extrayendo configuración articular mediante mc.get_angles()...")
    angulos = mc.get_angles()

    # Validación e interceptación de posiciones fuera de rango
    if not angulos or len(angulos) < 3:
        print(f"  [!] Alerta: El firmware determinó que la posición es inalcanzable.")
        tabla_resultados.append({
            "Configuración": nombre,
            "Estado": "Fuera de Rango / Error IK",
            "J1 (°)": "-", "J2 (°)": "-", "J3 (°)": "-"
        })
        continue

    # Registro exitoso de variables articulares
    print(f"  [OK] Solución IK acoplada: J1={round(angulos[0],1)}°, J2={round(angulos[1],1)}°, J3={round(angulos[2],1)}°")
    tabla_resultados.append({
        "Configuración": nombre,
        "Estado": "OK (Alcanzado)",
        "J1 (°)": round(angulos[0], 2),
        "J2 (°)": round(angulos[1], 2),
        "J3 (°)": round(angulos[2], 2)
    })

# Retorno de cortesía a Home para dejar el brazo en reposo mecánico
print("\n-> Finalizando rutina de prueba. Retornando a Home...")
mc.send_angles([0, 0, 0, 0, 0, 0], 40)
time.sleep(3.0)

# =====================================================================
# 4. DESPLIEGUE DEL REPORTE FINAL EN JUPYTER
# =====================================================================
print("\n====================================================================")
print("             TABLA DE RESULTADOS: CINEMÁTICA INVERSA API            ")
print("====================================================================\n")

df_ik = pd.DataFrame(tabla_resultados)
display(df_ik)

#Parte 3.2

import numpy as np
import pandas as pd

# =====================================================================
# PARÁMETROS DEL ROBOT
# =====================================================================
ALTURA_BASE = 134.75
ESLABÓN_1   = 110.0
ESLABÓN_2   = 96.0

POSICIONES_PRUEBA = [
    {"nombre": "Pos 1", "x": 120.0, "y":  100.0, "z": 200.0},
    {"nombre": "Pos 2", "x": 150.0, "y":  -50.0, "z": 150.0},
    {"nombre": "Pos 3", "x":   0.0, "y":  150.0, "z": 250.0},
    {"nombre": "Pos 4", "x":   0.0, "y":  300.0, "z": 400.0},
]


# =====================================================================
# IK ANALÍTICA — θ1 = atan2(y, x) + modelo planar 2R para θ2 y θ3
# =====================================================================
def calcular_ik_analitica(x, y, z):
    theta1               = np.arctan2(y, x)
    distancia_horizontal = np.sqrt(x**2 + y**2)
    altura_efectiva      = z - ALTURA_BASE
    cos_codo             = (distancia_horizontal**2 + altura_efectiva**2
                            - ESLABÓN_1**2 - ESLABÓN_2**2) / (2 * ESLABÓN_1 * ESLABÓN_2)

    if cos_codo < -1 or cos_codo > 1:
        return None

    theta3 = np.arctan2(-np.sqrt(1 - cos_codo**2), cos_codo)
    theta2 = np.arctan2(altura_efectiva, distancia_horizontal) \
           - np.arctan2(ESLABÓN_2 * np.sin(theta3), ESLABÓN_1 + ESLABÓN_2 * np.cos(theta3))

    return np.degrees(theta1), np.degrees(theta2), np.degrees(theta3)


# =====================================================================
# VERIFICACIÓN — Cinemática Directa para comprobar que los ángulos
# devuelven exactamente el punto original
# =====================================================================
def verificar_con_cinematica_directa(theta1, theta2, theta3):
    t1 = np.radians(theta1)
    t2 = np.radians(theta2)
    t3 = np.radians(theta3)
    x = np.cos(t1) * (ESLABÓN_1 * np.cos(t2) + ESLABÓN_2 * np.cos(t2 + t3))
    y = np.sin(t1) * (ESLABÓN_1 * np.cos(t2) + ESLABÓN_2 * np.cos(t2 + t3))
    z = ALTURA_BASE + ESLABÓN_1 * np.sin(t2) + ESLABÓN_2 * np.sin(t2 + t3)
    return x, y, z


# =====================================================================
# CALCULAR IK PARA CADA POSICIÓN Y VERIFICAR RESULTADO
# =====================================================================
tabla = []

for pos in POSICIONES_PRUEBA:
    nombre  = pos["nombre"]
    x, y, z = pos["x"], pos["y"], pos["z"]

    print(f"\n{'='*55}")
    print(f"  {nombre}  →  X={x}  Y={y}  Z={z}")
    print(f"{'='*55}")

    angulos = calcular_ik_analitica(x, y, z)

    if angulos is None:
        print(f"  [!] Fuera de rango — el brazo no alcanza este punto")
        tabla.append({"Posición": nombre, "Estado": "Fuera de rango",
                      "θ1 (°)": "-", "θ2 (°)": "-", "θ3 (°)": "-",
                      "FK→X": "-", "FK→Y": "-", "FK→Z": "-", "Err (mm)": "-"})
        continue

    theta1, theta2, theta3 = angulos
    fx, fy, fz = verificar_con_cinematica_directa(theta1, theta2, theta3)
    error_mm   = np.sqrt((fx - x)**2 + (fy - y)**2 + (fz - z)**2)

    print(f"  θ1 = atan2({y}, {x}) = {theta1:.3f}°")
    print(f"  θ2 (modelo 2R)       = {theta2:.3f}°")
    print(f"  θ3 (ley cosenos)     = {theta3:.3f}°")
    print(f"  Verificación FK:  X={fx:.2f}  Y={fy:.2f}  Z={fz:.2f}  |  Error={error_mm:.6f} mm")

    tabla.append({"Posición": nombre, "Estado": "OK",
                  "θ1 (°)": round(theta1, 3), "θ2 (°)": round(theta2, 3), "θ3 (°)": round(theta3, 3),
                  "FK→X": round(fx, 2), "FK→Y": round(fy, 2), "FK→Z": round(fz, 2),
                  "Err (mm)": round(error_mm, 6)})


# =====================================================================
# TABLA FINAL
# =====================================================================
print(f"\n{'='*55}")
print("  CELDA 2 — IK ANALÍTICA: θ1=atan2 + modelo 2R")
print(f"{'='*55}")
df = pd.DataFrame(tabla)
print(df.to_string(index=False))

#Parte 3.3

import numpy as np
import sympy as sp
import pandas as pd

# =====================================================================
# PARÁMETROS DEL ROBOT
# =====================================================================
ALTURA_BASE = 134.75
ESLABÓN_1   = 110.0
ESLABÓN_2   = 96.0

POSICIONES_PRUEBA = [
    {"nombre": "Pos 1", "x": 120.0, "y":  100.0, "z": 200.0},
    {"nombre": "Pos 2", "x": 150.0, "y":  -50.0, "z": 150.0},
    {"nombre": "Pos 3", "x":   0.0, "y":  150.0, "z": 250.0},
]


# =====================================================================
# MÉTODO 1 — IK ANALÍTICA
# =====================================================================
def calcular_ik_analitica(x, y, z):
    theta1               = np.arctan2(y, x)
    distancia_horizontal = np.sqrt(x**2 + y**2)
    altura_efectiva      = z - ALTURA_BASE
    cos_codo             = (distancia_horizontal**2 + altura_efectiva**2
                            - ESLABÓN_1**2 - ESLABÓN_2**2) / (2 * ESLABÓN_1 * ESLABÓN_2)

    if cos_codo < -1 or cos_codo > 1:
        return None

    theta3 = np.arctan2(-np.sqrt(1 - cos_codo**2), cos_codo)
    theta2 = np.arctan2(altura_efectiva, distancia_horizontal) \
           - np.arctan2(ESLABÓN_2 * np.sin(theta3), ESLABÓN_1 + ESLABÓN_2 * np.cos(theta3))

    return np.degrees(theta1), np.degrees(theta2), np.degrees(theta3)


# =====================================================================
# MÉTODO 2 — IK VÍA API (Jacobiano iterativo)
# =====================================================================
q1, q2, q3 = sp.symbols('q1 q2 q3')

FK_X = sp.cos(q1) * (ESLABÓN_1 * sp.cos(q2) + ESLABÓN_2 * sp.cos(q2 + q3))
FK_Y = sp.sin(q1) * (ESLABÓN_1 * sp.cos(q2) + ESLABÓN_2 * sp.cos(q2 + q3))
FK_Z = ALTURA_BASE + ESLABÓN_1 * sp.sin(q2) + ESLABÓN_2 * sp.sin(q2 + q3)

cinematica_directa  = sp.Matrix([FK_X, FK_Y, FK_Z])
jacobiano_simbolico = cinematica_directa.jacobian([q1, q2, q3])

def calcular_ik_jacobiano(x, y, z):
    objetivo  = np.array([x, y, z], dtype=float)
    angulos   = np.array([0.1, 0.1, -0.1])

    for iteracion in range(1, 201):
        valores_actuales = {q1: angulos[0], q2: angulos[1], q3: angulos[2]}
        posicion_actual  = np.array([float(cinematica_directa[i].subs(valores_actuales)) for i in range(3)])
        error            = objetivo - posicion_actual

        if np.linalg.norm(error) < 0.5:
            return np.degrees(angulos), iteracion

        jacobiano_numerico = np.array(jacobiano_simbolico.subs(valores_actuales)).astype(np.float64)
        angulos = angulos + 0.5 * (np.linalg.pinv(jacobiano_numerico) @ error)

    return np.degrees(angulos), 200


# =====================================================================
# UTILIDADES
# =====================================================================
def normalizar_angulo(angulo):
    return (angulo + 180) % 360 - 180

def error_angular(angulo_a, angulo_b):
    diferencia = abs(normalizar_angulo(angulo_a) - normalizar_angulo(angulo_b))
    return round(diferencia if diferencia <= 180 else 360 - diferencia, 2)

def punto_xyz_desde_angulos(theta1, theta2, theta3):
    t1, t2, t3 = np.radians(theta1), np.radians(theta2), np.radians(theta3)
    x = np.cos(t1) * (ESLABÓN_1 * np.cos(t2) + ESLABÓN_2 * np.cos(t2 + t3))
    y = np.sin(t1) * (ESLABÓN_1 * np.cos(t2) + ESLABÓN_2 * np.cos(t2 + t3))
    z = ALTURA_BASE + ESLABÓN_1 * np.sin(t2) + ESLABÓN_2 * np.sin(t2 + t3)
    return round(x, 2), round(y, 2), round(z, 2)


# =====================================================================
# COMPARAR AMBOS MÉTODOS PARA CADA POSICIÓN
# =====================================================================
tabla = []

for pos in POSICIONES_PRUEBA:
    nombre  = pos["nombre"]
    x, y, z = pos["x"], pos["y"], pos["z"]

    print(f"\n{'='*62}")
    print(f"  {nombre}  →  X={x}  Y={y}  Z={z}")
    print(f"{'='*62}")

    # Método 1
    angulos_analiticos = calcular_ik_analitica(x, y, z)
    J1_ana = normalizar_angulo(angulos_analiticos[0])
    J2_ana = normalizar_angulo(angulos_analiticos[1])
    J3_ana = normalizar_angulo(angulos_analiticos[2])
    fx_ana, fy_ana, fz_ana = punto_xyz_desde_angulos(J1_ana, J2_ana, J3_ana)
    error_ana = round(np.sqrt((fx_ana-x)**2 + (fy_ana-y)**2 + (fz_ana-z)**2), 4)
    print(f"  [Analítica]  J1={J1_ana:.2f}°  J2={J2_ana:.2f}°  J3={J3_ana:.2f}°  →  FK=({fx_ana},{fy_ana},{fz_ana})  Err={error_ana} mm")

    # Método 2
    angulos_jacobiano, n_iter = calcular_ik_jacobiano(x, y, z)
    J1_jac = normalizar_angulo(float(angulos_jacobiano[0]))
    J2_jac = normalizar_angulo(float(angulos_jacobiano[1]))
    J3_jac = normalizar_angulo(float(angulos_jacobiano[2]))
    fx_jac, fy_jac, fz_jac = punto_xyz_desde_angulos(J1_jac, J2_jac, J3_jac)
    error_jac = round(np.sqrt((fx_jac-x)**2 + (fy_jac-y)**2 + (fz_jac-z)**2), 4)
    print(f"  [Jacobiano]  J1={J1_jac:.2f}°  J2={J2_jac:.2f}°  J3={J3_jac:.2f}°  →  FK=({fx_jac},{fy_jac},{fz_jac})  Err={error_jac} mm  ({n_iter} iters)")

    # Diferencia
    dJ1 = error_angular(J1_ana, J1_jac)
    dJ2 = error_angular(J2_ana, J2_jac)
    dJ3 = error_angular(J3_ana, J3_jac)
    misma_solucion = "SI" if dJ1 < 5 and dJ2 < 5 and dJ3 < 5 else "NO (sol. alternativa)"
    print(f"  [Diferencia] ΔJ1={dJ1}°  ΔJ2={dJ2}°  ΔJ3={dJ3}°  →  Misma solución: {misma_solucion}")

    tabla.append({
        "Posición"      : nombre,
        "J1 Ana (°)"    : round(J1_ana, 2), "J1 Jac (°)": round(J1_jac, 2), "ΔJ1 (°)": dJ1,
        "J2 Ana (°)"    : round(J2_ana, 2), "J2 Jac (°)": round(J2_jac, 2), "ΔJ2 (°)": dJ2,
        "J3 Ana (°)"    : round(J3_ana, 2), "J3 Jac (°)": round(J3_jac, 2), "ΔJ3 (°)": dJ3,
        "Err Ana (mm)"  : error_ana,
        "Err Jac (mm)"  : error_jac,
        "Misma solución": misma_solucion,
    })


# =====================================================================
# TABLA FINAL
# =====================================================================
print(f"\n{'='*62}")
print("   CELDA 3 — COMPARACIÓN: IK ANALÍTICA vs JACOBIANO")
print(f"{'='*62}")
df = pd.DataFrame(tabla)
print(df.to_string(index=False))

#Parte 3.4

import numpy as np
import sympy as sp
import pandas as pd

# =====================================================================
# PARÁMETROS DEL ROBOT
# =====================================================================
ALTURA_BASE  = 134.75
ESLABÓN_1    = 110.0
ESLABÓN_2    = 96.0

POSICIONES_PRUEBA = [
    {"nombre": "Pos 1", "x": 120.0, "y":  100.0, "z": 200.0},
    {"nombre": "Pos 2", "x": 150.0, "y":  -50.0, "z": 150.0},
    {"nombre": "Pos 3", "x":   0.0, "y":  150.0, "z": 250.0},
]

# =====================================================================
# MÉTODO 1 — IK ANALÍTICA
# Fórmula cerrada: θ1 = atan2(y,x), luego modelo planar 2R para θ2 y θ3
# =====================================================================
def calcular_ik_analitica(x, y, z):
    theta1 = np.arctan2(y, x)

    distancia_horizontal = np.sqrt(x**2 + y**2)
    altura_efectiva      = z - ALTURA_BASE

    cos_theta3 = (distancia_horizontal**2 + altura_efectiva**2
                  - ESLABÓN_1**2 - ESLABÓN_2**2) / (2 * ESLABÓN_1 * ESLABÓN_2)

    if cos_theta3 < -1 or cos_theta3 > 1:
        return None

    theta3 = np.arctan2(-np.sqrt(1 - cos_theta3**2), cos_theta3)
    theta2 = np.arctan2(altura_efectiva, distancia_horizontal) \
           - np.arctan2(ESLABÓN_2 * np.sin(theta3),
                        ESLABÓN_1 + ESLABÓN_2 * np.cos(theta3))

    return np.degrees(theta1), np.degrees(theta2), np.degrees(theta3)


# =====================================================================
# MÉTODO 2 — IK VÍA API (Jacobiano iterativo)
# Simula mc.send_coords() + mc.get_angles()
# =====================================================================
q1, q2, q3 = sp.symbols('q1 q2 q3')

posicion_x = sp.cos(q1) * (ESLABÓN_1 * sp.cos(q2) + ESLABÓN_2 * sp.cos(q2 + q3))
posicion_y = sp.sin(q1) * (ESLABÓN_1 * sp.cos(q2) + ESLABÓN_2 * sp.cos(q2 + q3))
posicion_z = ALTURA_BASE + ESLABÓN_1 * sp.sin(q2) + ESLABÓN_2 * sp.sin(q2 + q3)

cinematica_directa = sp.Matrix([posicion_x, posicion_y, posicion_z])
jacobiano_simbolico = cinematica_directa.jacobian([q1, q2, q3])

def calcular_ik_jacobiano(x, y, z):
    objetivo      = np.array([x, y, z], dtype=float)
    angulos_rad   = np.array([0.1, 0.1, -0.1])

    for iteracion in range(1, 201):
        valores_actuales = {q1: angulos_rad[0], q2: angulos_rad[1], q3: angulos_rad[2]}

        posicion_actual = np.array([
            float(cinematica_directa[0].subs(valores_actuales)),
            float(cinematica_directa[1].subs(valores_actuales)),
            float(cinematica_directa[2].subs(valores_actuales)),
        ])

        error_posicion = objetivo - posicion_actual

        if np.linalg.norm(error_posicion) < 0.5:
            return np.degrees(angulos_rad), iteracion

        jacobiano_numerico  = np.array(jacobiano_simbolico.subs(valores_actuales)).astype(np.float64)
        jacobiano_inverso   = np.linalg.pinv(jacobiano_numerico)
        correccion_angulos  = jacobiano_inverso @ error_posicion

        angulos_rad = angulos_rad + 0.5 * correccion_angulos

    return np.degrees(angulos_rad), 200


# =====================================================================
# UTILIDADES DE COMPARACIÓN ANGULAR
# =====================================================================
def normalizar_angulo(angulo):
    return (angulo + 180) % 360 - 180

def error_entre_angulos(angulo_a, angulo_b):
    diferencia = abs(normalizar_angulo(angulo_a) - normalizar_angulo(angulo_b))
    return round(diferencia if diferencia <= 180 else 360 - diferencia, 2)

def clasificar_causa(error_j1, error_j2, error_j3):
    if error_j1 < 5 and error_j2 < 5 and error_j3 < 5:
        return "Error numérico residual (misma solución)"
    return "Solución alternativa (codo arriba vs codo abajo)"


# =====================================================================
# COMPARACIÓN POSICIÓN POR POSICIÓN
# =====================================================================
tabla_errores = []

for pos in POSICIONES_PRUEBA:
    nombre = pos["nombre"]
    x, y, z = pos["x"], pos["y"], pos["z"]

    print(f"\n{'='*60}")
    print(f"  {nombre}  →  X={x}  Y={y}  Z={z}")
    print(f"{'='*60}")

    # Método 1
    resultado_analitico = calcular_ik_analitica(x, y, z)
    J1_analitico = normalizar_angulo(resultado_analitico[0])
    J2_analitico = normalizar_angulo(resultado_analitico[1])
    J3_analitico = normalizar_angulo(resultado_analitico[2])
    print(f"  [Analítica]  J1={J1_analitico:.2f}°  J2={J2_analitico:.2f}°  J3={J3_analitico:.2f}°")

    # Método 2
    resultado_jacobiano, iteraciones = calcular_ik_jacobiano(x, y, z)
    J1_jacobiano = normalizar_angulo(float(resultado_jacobiano[0]))
    J2_jacobiano = normalizar_angulo(float(resultado_jacobiano[1]))
    J3_jacobiano = normalizar_angulo(float(resultado_jacobiano[2]))
    print(f"  [Jacobiano]  J1={J1_jacobiano:.2f}°  J2={J2_jacobiano:.2f}°  J3={J3_jacobiano:.2f}°  ({iteraciones} iters)")

    # Errores
    error_J1 = error_entre_angulos(J1_analitico, J1_jacobiano)
    error_J2 = error_entre_angulos(J2_analitico, J2_jacobiano)
    error_J3 = error_entre_angulos(J3_analitico, J3_jacobiano)
    error_total = round(np.sqrt(error_J1**2 + error_J2**2 + error_J3**2), 2)
    causa = clasificar_causa(error_J1, error_J2, error_J3)
    print(f"  [Error]      ΔJ1={error_J1}°  ΔJ2={error_J2}°  ΔJ3={error_J3}°  →  {causa}")

    tabla_errores.append({
        "Posición"       : nombre,
        "ΔJ1 (°)"        : error_J1,
        "ΔJ2 (°)"        : error_J2,
        "ΔJ3 (°)"        : error_J3,
        "Error total (°)": error_total,
        "Causa"          : causa,
    })


# =====================================================================
# TABLA FINAL DE ERRORES
# =====================================================================
print(f"\n{'='*60}")
print("    TABLA DE ERRORES EN GRADOS: ANALÍTICA vs API")
print(f"{'='*60}")
df_errores = pd.DataFrame(tabla_errores)
print(df_errores.to_string(index=False))


# =====================================================================
# DISCUSIÓN DE CAUSAS
# =====================================================================
print(f"""
{'='*60}
DISCUSIÓN DE CAUSAS
{'='*60}

CAUSA 1 — Error numérico residual
  El Jacobiano para cuando el error de posición es menor a 0.5 mm,
  no cuando los ángulos son exactos. Ese margen genera una pequeña
  diferencia angular respecto a la solución analítica (< 1°).
  Es inherente a todo método iterativo y aceptable en robótica.

CAUSA 2 — Solución alternativa (codo arriba vs codo abajo)
  Para un mismo punto XYZ existen dos configuraciones válidas:

      Analítica  →  elige CODO ARRIBA  (J2 positivo)
      Jacobiano  →  elige CODO ABAJO   (J2 negativo)

  El Jacobiano llega a esa rama porque su semilla inicial es
  q = [0.1, 0.1, -0.1] rad, que apunta hacia codo abajo.
  Ambas soluciones son físicamente correctas.

CONCLUSIÓN
  Los errores grandes en J2/J3 no son fallos del algoritmo.
  Son configuraciones distintas que alcanzan el mismo punto.
  El único error verdadero es el residual numérico (< 1°).
{'='*60}
""")

#Parte 3.5

import numpy as np
import sympy as sp
import pandas as pd

# =====================================================================
# PARÁMETROS DEL ROBOT
# =====================================================================
ALTURA_BASE = 134.75
ESLABÓN_1   = 110.0
ESLABÓN_2   = 96.0


# =====================================================================
# PARTE 1 — ESPACIO DE TRABAJO ALCANZABLE
# Un punto es alcanzable si su distancia al hombro está entre
# el alcance mínimo y el alcance máximo del brazo
# =====================================================================
ALCANCE_MÁXIMO = ESLABÓN_1 + ESLABÓN_2      # brazo completamente estirado = 206 mm
ALCANCE_MÍNIMO = abs(ESLABÓN_1 - ESLABÓN_2) # brazo completamente plegado  =  14 mm

POSICIONES_ESPACIO_TRABAJO = [
    {"nombre": "Dentro del rango",  "x": 120.0, "y": 100.0, "z": 200.0},
    {"nombre": "Dentro del rango",  "x": 150.0, "y": -50.0, "z": 150.0},
    {"nombre": "Dentro del rango",  "x":   0.0, "y": 150.0, "z": 250.0},
    {"nombre": "Fuera — muy lejos", "x":   0.0, "y": 300.0, "z": 400.0},
    {"nombre": "Fuera — muy cerca", "x":   5.0, "y":   0.0, "z": 134.75},
]

def verificar_alcance(x, y, z):
    distancia_horizontal = np.sqrt(x**2 + y**2)
    altura_efectiva      = z - ALTURA_BASE
    distancia_al_hombro  = np.sqrt(distancia_horizontal**2 + altura_efectiva**2)

    if distancia_al_hombro > ALCANCE_MÁXIMO:
        return "FUERA", distancia_al_hombro, f"distancia {distancia_al_hombro:.1f} mm supera el máximo de {ALCANCE_MÁXIMO} mm"
    if distancia_al_hombro < ALCANCE_MÍNIMO:
        return "FUERA", distancia_al_hombro, f"distancia {distancia_al_hombro:.1f} mm es menor al mínimo de {ALCANCE_MÍNIMO} mm"
    return "DENTRO", distancia_al_hombro, f"distancia {distancia_al_hombro:.1f} mm está entre {ALCANCE_MÍNIMO} y {ALCANCE_MÁXIMO} mm"

print("=" * 60)
print("  PARTE 1 — ESPACIO DE TRABAJO ALCANZABLE")
print("=" * 60)
print(f"  Alcance máximo (brazo estirado) = {ALCANCE_MÁXIMO} mm")
print(f"  Alcance mínimo (brazo plegado)  = {ALCANCE_MÍNIMO} mm")
print()

tabla_alcance = []
for pos in POSICIONES_ESPACIO_TRABAJO:
    nombre = pos["nombre"]
    x, y, z = pos["x"], pos["y"], pos["z"]
    estado, distancia, detalle = verificar_alcance(x, y, z)
    print(f"  X={x:6}  Y={y:6}  Z={z:6}  →  {estado}  ({detalle})")
    tabla_alcance.append({
        "X": x, "Y": y, "Z": z,
        "Distancia al hombro (mm)": round(distancia, 1),
        "Estado": estado,
    })

print()
df_alcance = pd.DataFrame(tabla_alcance)
print(df_alcance.to_string(index=False))


# =====================================================================
# PARTE 2 — CONFIGURACIONES SINGULARES
# Una configuración es singular cuando det(J) ≈ 0
# El robot pierde movilidad en alguna dirección
# =====================================================================
q1, q2, q3 = sp.symbols('q1 q2 q3')

posicion_x = sp.cos(q1) * (ESLABÓN_1 * sp.cos(q2) + ESLABÓN_2 * sp.cos(q2 + q3))
posicion_y = sp.sin(q1) * (ESLABÓN_1 * sp.cos(q2) + ESLABÓN_2 * sp.cos(q2 + q3))
posicion_z = ALTURA_BASE + ESLABÓN_1 * sp.sin(q2) + ESLABÓN_2 * sp.sin(q2 + q3)

cinematica_directa  = sp.Matrix([posicion_x, posicion_y, posicion_z])
jacobiano_simbolico = cinematica_directa.jacobian([q1, q2, q3])

UMBRAL_SINGULARIDAD = 1e-3

CONFIGURACIONES_PRUEBA = [
    {"nombre": "Normal",              "theta1": 0.5,  "theta2": 0.5,  "theta3": -0.5},
    {"nombre": "Brazo estirado",      "theta1": 0.0,  "theta2": 0.0,  "theta3":  0.0},
    {"nombre": "Brazo plegado",       "theta1": 0.0,  "theta2": 0.0,  "theta3":  np.pi},
    {"nombre": "Base sobre eje Z",    "theta1": 0.0,  "theta2": 0.8,  "theta3": -0.5},
]

def calcular_determinante_jacobiano(theta1, theta2, theta3):
    valores_angulos    = {q1: theta1, q2: theta2, q3: theta3}
    jacobiano_numerico = np.array(jacobiano_simbolico.subs(valores_angulos)).astype(np.float64)
    return abs(np.linalg.det(jacobiano_numerico))

print()
print("=" * 60)
print("  PARTE 2 — CONFIGURACIONES SINGULARES")
print("=" * 60)
print(f"  Umbral de singularidad: det(J) < {UMBRAL_SINGULARIDAD}")
print()

tabla_singularidades = []
for config in CONFIGURACIONES_PRUEBA:
    nombre  = config["nombre"]
    theta1  = config["theta1"]
    theta2  = config["theta2"]
    theta3  = config["theta3"]

    determinante = calcular_determinante_jacobiano(theta1, theta2, theta3)
    es_singular  = determinante < UMBRAL_SINGULARIDAD
    estado       = "SINGULAR" if es_singular else "Normal"

    print(f"  {nombre:<22}  det(J) = {determinante:.2e}  →  {estado}")
    tabla_singularidades.append({
        "Configuración": nombre,
        "θ1 (rad)": theta1,
        "θ2 (rad)": theta2,
        "θ3 (rad)": round(theta3, 3),
        "det(J)": f"{determinante:.2e}",
        "Estado": estado,
    })

print()
df_singularidades = pd.DataFrame(tabla_singularidades)
print(df_singularidades.to_string(index=False))


# =====================================================================
# PARTE 3 — EXPLICACIÓN DE CADA CASO
# =====================================================================
print(f"""
{'='*60}
  PARTE 3 — EXPLICACIÓN DE CADA CASO
{'='*60}

ESPACIO DE TRABAJO
  El brazo solo puede llegar a puntos cuya distancia al hombro
  esté entre {ALCANCE_MÍNIMO} mm y {ALCANCE_MÁXIMO} mm.
  Fuera de ese rango el triángulo geométrico es imposible.

SINGULARIDAD — Brazo estirado (θ3 = 0°)
  El codo está completamente extendido.
  El brazo no puede moverse en la dirección radial.
  det(J) = 0 exacto.

SINGULARIDAD — Brazo plegado (θ3 = 180°)
  El antebrazo apunta en sentido contrario al brazo superior.
  Misma pérdida de movilidad que en el caso anterior.
  det(J) ≈ 0.

SINGULARIDAD — Base sobre el eje Z (θ1 indefinido)
  Ocurre cuando x = 0 e y = 0.
  atan2(0, 0) es matemáticamente indefinido.
  La base puede girar cualquier ángulo sin mover la punta.
  det(J) ≈ 0.
{'='*60}
""")