# -*- coding: utf-8 -*-
"""Copia de kuka_arm_robot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddpIX4d-C2pvEmXoa1w_v5IiogRaCzFm
"""

import sympy as sp
from sympy import init_printing
from sympy.printing import latex
from sympy.physics.mechanics import dynamicsymbols

def custom_latex_printer(expr, **options):
    from IPython.display import Math, HTML
    from google.colab.output._publish import javascript
    url = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    javascript(content="""window.MathJax = {
        tex2jax: {
            inlineMath: [ ['$','$'] ],
            processEscapes: true
        }
        };""")
    javascript(url=url)
    return latex(expr, **options)

init_printing(use_latex='mathjax', latex_printer=custom_latex_printer) #configurado latex a impresion

"""## funciones de rotacion y translacion"""

def trans(x,y,z):
  M = sp.Matrix([[1, 0, 0, x],[0, 1, 0, y],[0, 0, 1, z],[0, 0, 0, 1]])
  return M

def rotx(ang):
  M = sp.Matrix([[1,0,0,0],[0, sp.cos(ang), -sp.sin(ang) , 0],[0, sp.sin(ang), sp.cos(ang),0 ],[0,0,0,1]])
  return M

def roty(ang):
  M = sp.Matrix([[ sp.cos(ang), 0, sp.sin(ang), 0],[0,1,0,0],[-sp.sin(ang), 0, sp.cos(ang),0],[0,0,0,1]])
  return M

def rotz(ang):
  M = sp.Matrix([[ sp.cos(ang), -sp.sin(ang), 0, 0],[sp.sin(ang), sp.cos(ang),0, 0],[0,0,1,0], [0,0,0,1]])
  return M

"""## Denavit Hartenberg"""

def DH(theta,d,a,alpha):
  tr = rotz(theta)*trans(0,0,d)*trans(a,0,0)*rotx(alpha)
  return tr

#variables simbolicas
q1, q2, q3, q4, q5, q6= dynamicsymbols('q1 q2 q3 q4 q5 q6')
q1, q2, q3, q4, q5,q6

A1 = DH(q1, 131.56,  0, sp.pi/2)
A1

A2 = DH(q2,  0, 110.4, 0)
A2

A3 = DH(q3, 0, 96, 0)
A3

A4 = DH(q4, 66.39, 0, -sp.pi/2)
A4

A5 = DH(q5, 73.18,  0, sp.pi/2)
A5

A6 = DH(q6, 48.6, 0, 0)
A6

Total = A1*A2*A3*A4*A5*A6
Total

Total.subs({q1:0 ,q2:0,q3:0,q4:0, q5:0, q6:0})

Tots = sp.simplify(Total)
Tots

Total.subs({q1:0, q2:0, q3:0, q4:0, q5:0, q6:0})

# parte 4.4

# Commented out IPython magic to ensure Python compatibility.
# %%writefile collision_checker.py
# import numpy as np
# from pymycobot.mycobot import MyCobot
# import time
# 
# Z_MINIMO_SEGURO = 50.0
# MARGEN_ANGULO = 10.0
# 
# RANGOS_SEGUROS = {
#     'J1': (-158, 158),
#     'J2': (-125, 80),
#     'J3': (-140, 140),
#     'J4': (-135, 135),
#     'J5': (-155, 155),
#     'J6': (-170, 170),
# }
# 
# D1 = 131.56
# A2 = 110.4
# A3 = 96.0
# 
# def calcular_z_extremo(j1, j2, j3, j4, j5, j6):
#     t2 = np.radians(j2)
#     t3 = np.radians(j3)
#     z = D1 + A2 * np.sin(t2) + A3 * np.sin(t2 + t3)
#     return round(z, 2)
# 
# def verificar_altura(j1, j2, j3, j4, j5, j6):
#     z = calcular_z_extremo(j1, j2, j3, j4, j5, j6)
#     if z < Z_MINIMO_SEGURO:
#         print(f'[COLISION] Z={z:.1f} mm < minimo {Z_MINIMO_SEGURO} mm - BLOQUEADO')
#         return False
#     print(f'[OK] Z={z:.1f} mm - altura segura')
#     return True
# 
# def verificar_rangos(j1, j2, j3, j4, j5, j6):
#     angulos = [j1, j2, j3, j4, j5, j6]
#     nombres = ['J1','J2','J3','J4','J5','J6']
#     for nombre, angulo in zip(nombres, angulos):
#         minimo, maximo = RANGOS_SEGUROS[nombre]
#         if angulo < minimo or angulo > maximo:
#             print(f'[COLISION] {nombre}={angulo}° fuera de rango - BLOQUEADO')
#             return False
#     print('[OK] Todos los angulos dentro de rangos seguros')
#     return True
# 
# def es_movimiento_seguro(j1, j2, j3, j4, j5, j6):
#     ok_rangos = verificar_rangos(j1, j2, j3, j4, j5, j6)
#     ok_altura = verificar_altura(j1, j2, j3, j4, j5, j6)
#     return ok_rangos and ok_altura
# 
# def mover_seguro(mc, angulos, velocidad=30):
#     j1,j2,j3,j4,j5,j6 = angulos
#     if es_movimiento_seguro(j1,j2,j3,j4,j5,j6):
#         mc.send_angles(angulos, velocidad)
#         time.sleep(2)
#         print(f'[EJECUTADO] Movimiento a {angulos}')
#         return True
#     else:
#         print(f'[BLOQUEADO] Movimiento a {angulos} cancelado')
#         return False

from pymycobot.mycobot import MyCobot
from collision_checker import mover_seguro
import time

mc = MyCobot('/dev/ttyUSB0', 1000000)
mc.power_on()
time.sleep(0.5)

# Prueba 1: posicion normal
print('=== PRUEBA 1 ===')
mover_seguro(mc, [0, 0, 0, 0, 0, 0], 30)

# Prueba 2: debe bloquearse
print('=== PRUEBA 2 ===')
mover_seguro(mc, [0, -90, 0, 0, 0, 0], 30)

# Prueba 3: debe bloquearse
print('=== PRUEBA 3 ===')
mover_seguro(mc, [0, 0, 160, 0, 0, 0], 30)

# Prueba 4: posicion de agarre
print('=== PRUEBA 4 ===')
mover_seguro(mc, [30, -20, 60, 0, 0, 0], 30)